---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboottingg
  labels:
    app: springboottingg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboottingg
  template:
    metadata:
      labels:
        app: springboottingg
    spec:
      containers:
        - name: springboottingg
          image: docker.io/phengbunath/springboottingg:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
